version: '3.8'

services:
  hh-watcher:
    build: .
    container_name: hh-watcher
    volumes:
      # Монтируем папку с данными для сохранения результатов
      - ./data:/app/data
      - ./report_oct5:/app/report_oct5
      - ./report_dynamics:/app/report_dynamics
      - ./report_automated:/app/report_automated
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Vladivostok
    # Команды для разных задач
    command: >
      sh -c "
        echo '🚀 Запуск HH_Watcher...' &&
        python sales_parser.py &&
        python zakup_parser.py &&
        python vacancy_analysis_oct5.py &&
        python vacancy_dynamics_comparison.py &&
        python create_automated_report.py &&
        echo '✅ Все отчёты созданы!'
      "
    
  # Отдельный сервис для только парсинга
  hh-parser:
    build: .
    container_name: hh-parser
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Vladivostok
    command: >
      sh -c "
        echo '📊 Парсинг данных...' &&
        python sales_parser.py &&
        python zakup_parser.py &&
        echo '✅ Парсинг завершён!'
      "
    
  # Отдельный сервис для только анализа
  hh-analyzer:
    build: .
    container_name: hh-analyzer
    volumes:
      - ./data:/app/data
      - ./report_oct5:/app/report_oct5
      - ./report_dynamics:/app/report_dynamics
      - ./report_automated:/app/report_automated
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Vladivostok
    command: >
      sh -c "
        echo '📈 Анализ данных...' &&
        python vacancy_analysis_oct5.py &&
        python vacancy_dynamics_comparison.py &&
        python create_automated_report.py &&
        echo '✅ Анализ завершён!'
      "

